# Site settings
title: Ngocok
name: Ngocok # your name
email: ngentot@waifu.club  # your email address
description: >
  tukang translate hentai mango
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ngocok.github.io" # the base hostname & protocol for your site
#twitter_username: itisbenjamin1 # your Twitter username
#github_username: itisbenjamin # your Github username
disqus_username: ngocok # your disqus username

# google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
